### ISSUE TITLE
简化Single Swap（XMath）

### ISSUE THREAD

**Issue by tturbulence** [xdefilab/xdefi-base#28]
在前端约束情况下单次Swap涉及一个简化判断：wO/wI是否为1或2或1/2或其他浮点数

1: 跳过计算（重要紧急）
2: 裸乘（重要）
0.5: 引导用户反向裸乘（重要）
其他: 其他

建议：
64-73 原始

public pure returns (uint256 tokenAmountOut) {
        uint256 weightRatio = tokenWeightIn.bdiv(tokenWeightOut);
        uint256 adjustedIn = BONE.bsub(swapFee);
        adjustedIn = tokenAmountIn.bmul(adjustedIn);
        uint256 y = tokenBalanceIn.bdiv(tokenBalanceIn.badd(adjustedIn));
        uint256 foo = y.bpow(weightRatio);
        uint256 bar = BONE.bsub(foo);
        tokenAmountOut = tokenBalanceOut.bmul(bar);
        return tokenAmountOut;
    }

修改

public pure returns (uint256 tokenAmountOut) {
        if (tokenWeightIn==tokenWightOut){
            uint256 weightRatio = 1;
        }else if (tokenWeightIn>>1==tokenWightOut){
            uint256 weightRatio = 2;
        } else{
            uint256 weightRatio = tokenWeightIn.bdiv(tokenWeightOut);
        }
        uint256 adjustedIn = BONE.bsub(swapFee);
        adjustedIn = tokenAmountIn.bmul(adjustedIn);
        uint256 y = tokenBalanceIn.bdiv(tokenBalanceIn.badd(adjustedIn));
        if (tokenWeightIn==tokenWightOut){
            uint256 foo = y;
        }else if (tokenWeightIn>>1==tokenWightOut){
            uint256 foo = y.bmul(y);
        } else{
            uint256 foo = y.bpow(weightRatio);
        }
        uint256 bar = BONE.bsub(foo);
        tokenAmountOut = tokenBalanceOut.bmul(bar);
        return tokenAmountOut;
    }

92-101行

原始

public pure returns (uint256 tokenAmountIn) {
        uint256 weightRatio = tokenWeightOut.bdiv(tokenWeightIn);
        uint256 diff = tokenBalanceOut.bsub(tokenAmountOut);
        uint256 y = tokenBalanceOut.bdiv(diff);
        uint256 foo = y.bpow(weightRatio);
        foo = foo.bsub(BONE);
        tokenAmountIn = BONE.bsub(swapFee);
        tokenAmountIn = tokenBalanceIn.bmul(foo).bdiv(tokenAmountIn);
        return tokenAmountIn;
    }
修改

public pure returns (uint256 tokenAmountIn) {
        if (tokenWeightOut==tokenWeightIn){
            uint256 weightRatio = 1;
        }else if (tokenWeightOut>>1==tokenWeightIn){
            uint256 weightRatio = 2;
        } else{
            uint256 weightRatio = tokenWeightOut.bdiv(tokenWeightIn);
        }
        uint256 diff = tokenBalanceOut.bsub(tokenAmountOut);
        uint256 y = tokenBalanceOut.bdiv(diff);
        if (tokenWeightOut==tokenWeightIn){
            uint256 foo = y;
        }else if (tokenWeightOut>>1==tokenWeightIn){
            uint256 foo = y.bmul(y);
        } else{
            uint256 foo = y.bpow(weightRatio);
        }
        foo = foo.bsub(BONE);
        tokenAmountIn = BONE.bsub(swapFee);
        tokenAmountIn = tokenBalanceIn.bmul(foo).bdiv(tokenAmountIn);
        return tokenAmountIn;
    }

**Comment by wuyxiquanquan** [comment]
这是哪个文件里的64-73行？

**Comment by xdefilab** [comment]
> 这是哪个文件里的64-73行？

XMath.sol

**Comment by xdefilab** [comment]
https://github.com/xdefilab/xdefi-base/pull/29

**Comment by tturbulence** [comment]
More suggestions: Add conditions for weight ratio @1,2,4,8 so that calling a simpler version of function bpowi

**Comment by xdefilab** [comment]
fixed
